get:
  summary: 개인 정보 일부 제공
  tags:
    - config
  parameters:
    $ref: '../../components/config/getPersonalInfo.yml#/GetPersonalInfoParameters'
  responses:
    '200':
      description: 정보 제공 성공
      content:
        application/json:
          schema:
            $ref: '../../components/config/getPersonalInfo.yml#/GetPersonalInfoSuccessResponse'
    '400':
      description: 유효하지 않은 인증수단
      content:
        application/json:
          schema:
            $ref: '../../components/config/getPersonalInfo.yml#/ErrorResponseInvalidToken'
    '500':
      description: 내부 서버 오류
      content:
        application/json:
          schema:
            $ref: '../../components/config/getPersonalInfo.yml#/ErrorResponseInternalServer'