post:
  summary: 비밀번호 변경
  tags:
    - config
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/config/setPass.yml#/SetPassRequest'
  responses:
    '200':
      description: 비밀번호 변경 성공
      content:
        application/json:
          schema:
            $ref: '../../components/config/setPass.yml#/SetPassSuccessResponse'
    '400':
      description: 유효하지 않은 인증수단
      content:
        application/json:
          schema:
            $ref: '../../components/config/setPass.yml#/ErrorResponseInvalidToken'
    '404':
      description: 존재하지 않는 이용자
      content:
        application/json:
          schema:
            $ref: '../../components/config/setPass.yml#/ErrorResponseNotUser'
    '500':
      description: 내부 서버 오류
      content:
        application/json:
          schema:
            $ref: '../../components/config/setPass.yml#/ErrorResponseInternalServer'

    