LogoutRequest:
  type: object
  properties:
    accessToken:
      type: string
  required:
    - accessToken

LogoutSuccessResponse:
  type: object
  properties:
    success:
      type: boolean
      example: true

ErrorResponseInvalidToken:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: 유효하지 않은 로그아웃 수단입니다

ErrorResponseInternalServer:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: 내부 서버 오류입니다
