SetAliasNameRequest:
  type: object
  properties:
    accessToken:
      type: string
    name:
      type: string
  required:
    - accessToken

SetAliasNameSuccessResponse:
  type: object
  properties:
    success:
      type: boolean
      example: true

ErrorResponseInvalidToken:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: 유효하지 않은 인증수단

ErrorResponseNotUser:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: 존재하지 않는 이용자

ErrorResponseInternalServer:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: 내부 서버 오류
