SetSettingInfoRequest:
  type: object
  properties:
    accessToken:
      type: string
    alarm:
      type: boolean
    babyName:
      type: string
    babyBirth:
      type: string
      format: date
    dataEliminateDuration:
      type: integer
    coreTimeStart:
      type: integer
    coreTimeEnd:
      type: integer
  required:
    - accessToken
    - alarm
    - babyName
    - babyBirth
    - dataEliminateDuration
    - coreTimeStart
    - coreTimeEnd

SetSettingInfoSuccessResponse:
  type: object
  properties:
    success:
      type: boolean
      example: true

ErrorResponseInvalidToken:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: 유효하지 않은 인증 수단

ErrorResponseInternalServer:
  type: object
  properties:
    success:
      type: boolean
      example: false
    message:
      type: string
      example: 내부 서버 오류
