openapi: 3.0.0
info:
  title: kt-aivle-bigProject
  version: 0.2.0
  description: 6반 18조 swagger입니다

servers:
  - url: "{PROTOCOL}://{HOME_ADDRESS}:3000/api"
    variables:
      PROTOCOL:
        default: http
      HOME_ADDRESS:
        default: localhost

tags:
  - name: hello
    description: front-back 간 시범 통신용 api
  - name: auth
    description: 개인 정보 등록 또는 접근 시 별도 인증이 필요할 때 사용
  - name: emoteai
    description: 감정 판별 ai 기능이 필요할 시 사용하는 api
  - name: chatai
    description: chatbot 관련 ai 기능이 필요할 시 사용하는 api
  - name: dashboard
    description: dashboard 페이지 구성에 필요한 정보 요청 api
  - name: config
    description: config 페이지의 일반 설정을 저장 및 불러오는 api 

paths:
  /hello:
    $ref: './openapi/paths/hello.yml'
  /auth/login:
    $ref: './openapi/paths/login.yml'
  /auth/register:
    $ref: './openapi/paths/register.yml'