openapi: 3.0.0
info:
  title: kt-aivle-bigProject
  version: 0.2.0
  description: 6반 18조 swagger입니다

servers:
  - url: "{PROTOCOL}://{HOME_ADDRESS}:3000/api"
    variables:
      PROTOCOL:
        default: http
      HOME_ADDRESS:
        default: localhost

tags:
  - name: hello
    description: front-back 간 시범 통신용 api
  - name: auth
    description: 개인 정보 등록 또는 접근 시 별도 인증이 필요할 때 사용
  - name: emoteai
    description: 감정 판별 ai 기능이 필요할 시 사용하는 api
  - name: chatai
    description: chatbot 관련 ai 기능이 필요할 시 사용하는 api
  - name: dashboard
    description: dashboard 페이지 구성에 필요한 정보 요청 api
  - name: config
    description: config 페이지의 일반 설정을 저장 및 불러오는 api
  - name: admin
    description: 공지사항 CRUD 및 관리자 계정 api

paths:
  /hello:
    $ref: './openapi/paths/hello.yml'
  /auth/login:
    $ref: './openapi/paths/auth/login.yml'
  /auth/sendVerificationCode:
    $ref: './openapi/paths/auth/sendVerificationCode.yml'
  /auth/checkVerificationCode:
    $ref: './openapi/paths/auth/checkVerificationCode.yml'
  /auth/checkEmail:
    $ref: './openapi/paths/auth/checkEmail.yml'
  /auth/checkPass:
    $ref: './openapi/paths/auth/checkPass.yml'
  /auth/register:
    $ref: './openapi/paths/auth/register.yml'
  /auth/findEmail:
    $ref: './openapi/paths/auth/findEmail.yml'
  /auth/findPass:
    $ref: './openapi/paths/auth/findPass.yml'
  /config/getSettingInfo:
    $ref: './openapi/paths/config/getSettingInfo.yml'
  /config/setSettingInfo:
    $ref: './openapi/paths/config/setSettingInfo.yml'
  /config/getPeronalInfo:
    $ref: './openapi/paths/config/getPersonalInfo.yml'
  /config/logout:
    $ref: './openapi/paths/config/logout.yml'
  /config/deleteUser:
    $ref: './openapi/paths/config/deleteUser.yml'
  /config/setProfileImage:
    $ref: './openapi/paths/config/setProfileImage.yml'
  /config/getProfileImage:
    $ref: './openapi/paths/config/getProfileImage.yml'
  /config/getAliasName:
    $ref: './openapi/paths/config/getAliasName.yml'
  /config/setAliasName:
    $ref: './openapi/paths/config/setAliasName.yml'
  /config/setPass:
    $ref: './openapi/paths/config/setPass.yml'
  /admin/createNotice:
    $ref: './openapi/paths/admin/createNotice.yml'
  /admin/updateNotice:
    $ref: './openapi/paths/admin/updateNotice.yml'
  /admin/getNoticeList:
    $ref: './openapi/paths/admin/getNoticeList.yml'
  /admin/readNotice:
    $ref: './openapi/paths/admin/readNotice.yml'
  /admin/deleteNotice:
    $ref: './openapi/paths/admin/deleteNotice.yml'
  /dashboard/getBabyInfo:
    $ref: './openapi/paths/dashboard/getBabyInfo.yml'
  /dashboard/getBabyEmotionInfo:
    $ref: './openapi/paths/dashboard/getBabyEmotionInfo.yml'
  /dashboard/getBabyCoreTimeDataInfo:
    $ref: './openapi/paths/dashboard/getBabyCoreTimeDataInfo.yml'
  /dashboard/getBabyFrequencyInfo:
    $ref: './openapi/paths/dashboard/getBabyFrequencyInfo.yml'
